### ISSUE TITLE
Error thrown on indenting using with Lexima plugin

### ISSUE THREAD

**Issue by Akin909** [styled-components/vim-styled-components#54] opened 2018-12-27 13:51 UTC
Thanks for the amazing work @fleischie :heart_eyes: (plugin has been getting better and better :+1:). 

I've been encountering an error using this plugin with [cohama/lexima](https://github.com/cohama/lexima.vim). 

![lexima-error](https://user-images.githubusercontent.com/22454918/50482378-7a454980-09e6-11e9-9c9a-f7f48fecd917.png)

On trying to indent inside of JSX, I get the error above which I think relates to some interaction between lexima and this plugin at [this line](https://github.com/styled-components/vim-styled-components/blob/05e8e25b6e659b9eadb89c32098b15b2c49034eb/after/indent/javascript.vim#L153). I've tried using `delimitMate` instead or disabling it and it works fine with lexima removed. I'm not an expert in vimscript so not sure exactly whats going on, but the plugin is running the `GetStyledIndent` when I try and create an indent outside of a styled-component, which might be by design or a bug :thinking:.

I'm running Nvim 0.3.1 on Manjaro Linux, please let me know if there's any other details I can provide

**Comment by fleischie** [comment] 2018-12-27 19:48
Hello @Akin909 and thank you for your kind words, I'm trying my best. :smile:

Calling `GetStyledIndent` is in fact by design, because it wraps a call for non-styled-components for different javascript plugins. So that is ok, I guess.

I will try to look into it, because I initially suspect a naming conflict between this and that plugin, but yeah I will have to investigate this further of course. Just be patient because holidays and stuff.

I get back to you, if I need more information. Thanks again for the issue. :bowing_man:

**Comment by fleischie** [comment] 2018-12-27 21:12
Haha, I lied. :man_shrugging: I used the downtime between family obligations to look into this issue.

Would you be so kind to test out the `develop` branch? (Use `Plug 'styled-components/vim-styled-components', { 'branch': 'develop' }` if you use [junegunn/vim-plug](https://github.com/junegunn/vim-plug), but this depends on your plugin manager.)

The above mentioned error seems to vanish once I initialize the highlighted variable outside of its execution branch inside of the appropriate routine. So yeah... maybe it works.

Happy holidays. :v:

**Comment by Akin909** [comment] 2018-12-27 22:42
@fleischie thanks for looking at it so quickly :heart_eyes: , just tested out the develop branch and I'm not seeing the error anymore :+1: :100:

**Comment by fleischie** [comment] 2018-12-27 23:15
Cool. I'll marfe it as soon as I'll get the chance. 🚀

**Comment by fleischie** [comment] 2019-01-09 14:53
Hey @Akin909 

I totally forgot I was to cut a release from the changes made in `develop`. I just did that now, so feel free to try out the `main` branch of this plugin.

I close this issue now. Feel free to open a new one, if you should have more troubles.

Thanks again for your contribution. 🙇

**Closed by fleischie** 2019-01-09 14:53 UTC
